//
// UserAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class UserAPI {
    /**
     Получение брокерских счетов клиента

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func userAccountsGet(completion: @escaping ((_ data: UserAccountsResponse?,_ error: Error?) -> Void)) {
        userAccountsGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Получение брокерских счетов клиента
     - GET /user/accounts
     - 

     - :
       - type: http
       - name: sso_auth
     - examples: [{contentType=application/json, example={
  "payload" : {
    "accounts" : [ {
      "brokerAccountId" : "brokerAccountId",
      "brokerAccountType" : "Tinkoff"
    }, {
      "brokerAccountId" : "brokerAccountId",
      "brokerAccountType" : "Tinkoff"
    } ]
  },
  "trackingId" : "trackingId",
  "status" : "Ok"
}}]

     - returns: RequestBuilder<UserAccountsResponse> 
     */
    open class func userAccountsGetWithRequestBuilder() -> RequestBuilder<UserAccountsResponse> {
        let path = "/user/accounts"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<UserAccountsResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
