//
// CandlesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CandlesResponse: Codable {

    public var trackingId: String
    public var status: String
    public var payload: Candles

    public init(trackingId: String, status: String, payload: Candles) {
        self.trackingId = trackingId
        self.status = status
        self.payload = payload
    }


}

