//
// Currency.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum Currency: String, Codable {
    case rub = "RUB"
    case usd = "USD"
    case eur = "EUR"
    case gbp = "GBP"
    case hkd = "HKD"
    case chf = "CHF"
    case jpy = "JPY"
    case cny = "CNY"
    case _try = "TRY"
}