//
// Currencies.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Currencies: Codable {

    public var currencies: [CurrencyPosition]

    public init(currencies: [CurrencyPosition]) {
        self.currencies = currencies
    }


}

