//
// CurrencyPosition.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CurrencyPosition: Codable {

    public var currency: Currency
    public var balance: Double
    public var blocked: Double?

    public init(currency: Currency, balance: Double, blocked: Double?) {
        self.currency = currency
        self.balance = balance
        self.blocked = blocked
    }


}

