//
// InstrumentType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum InstrumentType: String, Codable {
    case stock = "Stock"
    case currency = "Currency"
    case bond = "Bond"
    case etf = "Etf"
}