//
// LimitOrderResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LimitOrderResponse: Codable {

    public var trackingId: String
    public var status: String
    public var payload: PlacedLimitOrder

    public init(trackingId: String, status: String, payload: PlacedLimitOrder) {
        self.trackingId = trackingId
        self.status = status
        self.payload = payload
    }


}

