//
// MarketOrderResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MarketOrderResponse: Codable {

    public var trackingId: String
    public var status: String
    public var payload: PlacedMarketOrder

    public init(trackingId: String, status: String, payload: PlacedMarketOrder) {
        self.trackingId = trackingId
        self.status = status
        self.payload = payload
    }


}

