//
// MarketOrderRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MarketOrderRequest: Codable {

    public var lots: Int
    public var operation: OperationType

    public init(lots: Int, operation: OperationType) {
        self.lots = lots
        self.operation = operation
    }


}

