//
// MarketInstrumentList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MarketInstrumentList: Codable {

    public var total: Double
    public var instruments: [MarketInstrument]

    public init(total: Double, instruments: [MarketInstrument]) {
        self.total = total
        self.instruments = instruments
    }


}

