//
// MarketInstrumentResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MarketInstrumentResponse: Codable {

    public var trackingId: String
    public var status: String
    public var payload: MarketInstrument

    public init(trackingId: String, status: String, payload: MarketInstrument) {
        self.trackingId = trackingId
        self.status = status
        self.payload = payload
    }


}

