//
// ModelError.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ModelError: Codable {

    public var trackingId: String
    public var status: String
    public var payload: ErrorPayload

    public init(trackingId: String, status: String, payload: ErrorPayload) {
        self.trackingId = trackingId
        self.status = status
        self.payload = payload
    }


}

