//
// MoneyAmount.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MoneyAmount: Codable {

    public var currency: Currency
    public var value: Double

    public init(currency: Currency, value: Double) {
        self.currency = currency
        self.value = value
    }


}

