//
// OperationStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Статус заявки */
public enum OperationStatus: String, Codable {
    case done = "Done"
    case decline = "Decline"
    case progress = "Progress"
}