//
// Operations.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Operations: Codable {

    public var operations: [Operation]

    public init(operations: [Operation]) {
        self.operations = operations
    }


}

