//
// OrderbookResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OrderbookResponse: Codable {

    public var trackingId: String
    public var status: String
    public var payload: Orderbook

    public init(trackingId: String, status: String, payload: Orderbook) {
        self.trackingId = trackingId
        self.status = status
        self.payload = payload
    }


}

