//
// OrderStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Статус заявки */
public enum OrderStatus: String, Codable {
    case new = "New"
    case partiallyFill = "PartiallyFill"
    case fill = "Fill"
    case cancelled = "Cancelled"
    case replaced = "Replaced"
    case pendingCancel = "PendingCancel"
    case rejected = "Rejected"
    case pendingReplace = "PendingReplace"
    case pendingNew = "PendingNew"
}