//
// OrderType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Тип заявки */
public enum OrderType: String, Codable {
    case limit = "Limit"
    case market = "Market"
}