//
// OrdersResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OrdersResponse: Codable {

    public var trackingId: String
    public var status: String
    public var payload: [Order]

    public init(trackingId: String, status: String, payload: [Order]) {
        self.trackingId = trackingId
        self.status = status
        self.payload = payload
    }


}

