//
// OrderResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OrderResponse: Codable {

    public var price: Double
    public var quantity: Int

    public init(price: Double, quantity: Int) {
        self.price = price
        self.quantity = quantity
    }


}

