//
// PlacedLimitOrder.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PlacedLimitOrder: Codable {

    public var orderId: String
    public var operation: OperationType
    public var status: OrderStatus
    public var rejectReason: String?
    /** Сообщение об ошибке */
    public var message: String?
    public var requestedLots: Int
    public var executedLots: Int
    public var commission: MoneyAmount?

    public init(orderId: String, operation: OperationType, status: OrderStatus, rejectReason: String?, message: String?, requestedLots: Int, executedLots: Int, commission: MoneyAmount?) {
        self.orderId = orderId
        self.operation = operation
        self.status = status
        self.rejectReason = rejectReason
        self.message = message
        self.requestedLots = requestedLots
        self.executedLots = executedLots
        self.commission = commission
    }


}

