//
// PortfolioCurrenciesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PortfolioCurrenciesResponse: Codable {

    public var trackingId: String
    public var status: String
    public var payload: Currencies

    public init(trackingId: String, status: String, payload: Currencies) {
        self.trackingId = trackingId
        self.status = status
        self.payload = payload
    }


}

