//
// Portfolio.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Portfolio: Codable {

    public var positions: [PortfolioPosition]

    public init(positions: [PortfolioPosition]) {
        self.positions = positions
    }


}

