//
// PortfolioPosition.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PortfolioPosition: Codable {

    public var figi: String
    public var ticker: String?
    public var isin: String?
    public var instrumentType: InstrumentType
    public var balance: Double
    public var blocked: Double?
    public var expectedYield: MoneyAmount?
    public var lots: Int
    public var averagePositionPrice: MoneyAmount?
    public var averagePositionPriceNoNkd: MoneyAmount?
    public var name: String

    public init(figi: String, ticker: String?, isin: String?, instrumentType: InstrumentType, balance: Double, blocked: Double?, expectedYield: MoneyAmount?, lots: Int, averagePositionPrice: MoneyAmount?, averagePositionPriceNoNkd: MoneyAmount?, name: String) {
        self.figi = figi
        self.ticker = ticker
        self.isin = isin
        self.instrumentType = instrumentType
        self.balance = balance
        self.blocked = blocked
        self.expectedYield = expectedYield
        self.lots = lots
        self.averagePositionPrice = averagePositionPrice
        self.averagePositionPriceNoNkd = averagePositionPriceNoNkd
        self.name = name
    }


}

