//
// SandboxSetPositionBalanceRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SandboxSetPositionBalanceRequest: Codable {

    public var figi: String?
    public var balance: Double

    public init(figi: String?, balance: Double) {
        self.figi = figi
        self.balance = balance
    }


}

