//
// SandboxRegisterResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SandboxRegisterResponse: Codable {

    public var trackingId: String
    public var status: String
    public var payload: SandboxAccount

    public init(trackingId: String, status: String, payload: SandboxAccount) {
        self.trackingId = trackingId
        self.status = status
        self.payload = payload
    }


}

