//
// SandboxRegisterRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SandboxRegisterRequest: Codable {

    public var brokerAccountType: BrokerAccountType?

    public init(brokerAccountType: BrokerAccountType?) {
        self.brokerAccountType = brokerAccountType
    }


}

