//
// TradeStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum TradeStatus: String, Codable {
    case normalTrading = "NormalTrading"
    case notAvailableForTrading = "NotAvailableForTrading"
}