//
// UserAccountsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserAccountsResponse: Codable {

    public var trackingId: String
    public var status: String
    public var payload: UserAccounts

    public init(trackingId: String, status: String, payload: UserAccounts) {
        self.trackingId = trackingId
        self.status = status
        self.payload = payload
    }


}

