//
// UserAccounts.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserAccounts: Codable {

    public var accounts: [UserAccount]

    public init(accounts: [UserAccount]) {
        self.accounts = accounts
    }


}

